# Generated by Django 2.2.5 on 2020-11-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('todo', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('checkbox', models.BooleanField(blank=True)),
                ('date_finished', models.DateField(auto_now=True)),
            ],
        ),
    ]
