# Generated by Django 2.2.5 on 2020-11-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201129_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datecompleted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
